### ISSUE TITLE
Please update the System.IO.Abstractions reference to version 17.2.3 or above

### ISSUE THREAD

**Issue by IgorMS-GH** [eqxmedianl/EQXMedia.TxFileSystem#7]
Using EQXMedia.TxFileSystem in conjunction with a direct reference to _System.IO.Abstractions_ in version 16.x or 17.x leads to a

> System.TypeLoadException: Method 'CreateSymbolicLink' in type 'EQXMedia.TxFileSystem.TxFile' from assembly 'EQXMedia.TxFileSystem, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

because several interfaces in _System.IO.Abstractions_ have been extended with additional methods since version 13.2.9.

**Comment by jarnokamminga** [comment]
@IgorMS-GH, I will make sure this gets in a new release soon.

**Comment by jarnokamminga** [comment]
These changes have already been made and have been merged into `dev` yesterday, @IgorMS-GH .

However, code coverage should be increased again, for it to become part of the upcoming release.

**Comment by IgorMS-GH** [comment]
> These changes have already been made and have been merged into `dev` yesterday, @IgorMS-GH .
> 
> However, code coverage should be increased again, for it to become part of the upcoming release.

Thanks for your quick reaction.
I'm really looking forward to the upcoming 2.2.0 release.

**Comment by jarnokamminga** [comment]
@IgorMS-GH, when you upgrade to `3.0.0-beta1` you can use those methods now too. 

In the near future I will be adding support for even more recent versions of `System.IO.Abstractions`.

**Comment by IgorMS-GH** [comment]
👍 for resuming development on this package and updating the `Systems.IO.Abstractions` dependency.
I have to confess that I've moved on to later versions than 17.2.3 in the meantime. I'd therefore very much appreciate your supporting even more recent versions.
I'm also wondering if you will consider switching to the `TestableIO.System.IO.Abstractions` / `TestableIO.System.IO.Abstractions.Wrappers` pair which introduces a separation between interfaces and (default) implementations.
